<?xml version="1.0" encoding="utf-8"?><Database Name="QLCH" Class="dbQLCHDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.0.212;Initial Catalog=QLCH;Persist Security Info=True;User ID=sa" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="QLCHConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account_Info" Member="Account_Infos">
    <Type Name="Account_Info">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Account" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CapDayHoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TyLeCauHoi" Member="TyLeCauHois">
    <Type Name="TyLeCauHoi">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Mon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Muc1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Muc2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Muc3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Accounts" Member="Accounts">
    <Type Name="Account">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CauHoi" Member="CauHois">
    <Type Name="CauHoi">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Khoi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_Mon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_LoaiCauHoi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MucDo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Chuong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Bai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaCauHoi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_Account" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="InUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChuongBai" Member="ChuongBais">
    <Type Name="ChuongBai">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_MonHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoChuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenChuong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaChuong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoBai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DapAn" Member="DapAns">
    <Type Name="DapAn">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_CauHoi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DapAn" Member="DapAn1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsTrue" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaDapAn" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeThi" Member="DeThis">
    <Type Name="DeThi">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongCauHoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Account" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_Mon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_LoaiDeThi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaDeThi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GiamThi1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GiamThi2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="InUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeThi_ChiTiet" Member="DeThi_ChiTiets">
    <Type Name="DeThi_ChiTiet">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_DeThi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_CauHoi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DapAn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID_DapAnDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiCauHoi" Member="LoaiCauHois">
    <Type Name="LoaiCauHoi">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoaiCauHoi" Member="LoaiCauHoi1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaLoai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonHoc" Member="MonHocs">
    <Type Name="MonHoc">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Khoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenMonHoc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SoCauHoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="InUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaMonHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.TaoBaiThiNgauNhien" Method="TaoBaiThiNgauNhien">
    <Parameter Name="ID_LoaiBaiThi" Parameter="iD_LoaiBaiThi" Type="System.String" DbType="NVarChar(1)" />
    <Parameter Name="ID_MonHoc" Parameter="iD_MonHoc" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ID_Acc" Parameter="iD_Acc" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="MaDe" Parameter="maDe" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TuBai" Parameter="tuBai" Type="System.Int32" DbType="Int" />
    <Parameter Name="DenBai" Parameter="denBai" Type="System.Int32" DbType="Int" />
    <Parameter Name="TongSoCau" Parameter="tongSoCau" Type="System.Int32" DbType="Int" />
    <Parameter Name="SLCauDe" Parameter="sLCauDe" Type="System.Int32" DbType="Int" />
    <Parameter Name="SLCauTB" Parameter="sLCauTB" Type="System.Int32" DbType="Int" />
    <Parameter Name="SLCauKho" Parameter="sLCauKho" Type="System.Int32" DbType="Int" />
    <Parameter Name="IsCreateAuto" Parameter="isCreateAuto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TieuDeBaiThi" Parameter="tieuDeBaiThi" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="NguoiTao" Parameter="nguoiTao" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="NguoikyDuyet" Parameter="nguoikyDuyet" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="GiaoVien1" Parameter="giaoVien1" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="GiaoVien2" Parameter="giaoVien2" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="GhiChu" Parameter="ghiChu" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="tuNgay" Type="System.Int32" DbType="Int" />
    <Parameter Name="tuThang" Type="System.Int32" DbType="Int" />
    <Parameter Name="tuNam" Type="System.Int32" DbType="Int" />
  </Function>
</Database>